---
spring:
  profiles: peer1
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8762/eureka/,http://172.16.2.176:8763/eureka/
server:
  port: 8761
  
---
spring:
  profiles: peer2
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/,http://172.16.2.176:8763/eureka/
server:
  port: 8762

---
spring:
  profiles: peer3
  application:
    name: eureka-server
eureka:
  instance:
    hostname: peer3
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/,http://172.16.2.176:8762/eureka/
server:
  port: 8763
